name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake zip

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install cmake zip

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20

      - name: Build project
        run: cmake --build build --config Release

      - name: Package release files (Linux & macOS)
        if: runner.os != 'Windows'
        run: |
          mkdir release_package
          cp build/BlackjackLab release_package/
          cp chart_generator.py release_package/
          zip -r blackjack-lab-${{ github.ref_name }}-${{ runner.os }}.zip release_package/

      - name: Package release files (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path release_package
          Copy-Item -Path build/Release/BlackjackLab.exe -Destination release_package/
          Copy-Item -Path chart_generator.py -Destination release_package/
          Compress-Archive -Path release_package\* -DestinationPath blackjack-lab-${{ github.ref_name }}-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-package
          path: |
            blackjack-lab-${{ github.ref_name }}-${{ runner.os }}.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List artifacts for debugging
        run: ls -R ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: ./artifacts/**/* 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
